name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Gradle Build
        run: ./gradlew build

      - name: Gradle Test
        run: ./gradlew test

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Docker build
        run: |
          docker build -t cicd-example .
          docker tag cicd-example pangnem/cicd-example:${GITHUB_SHA::7}
          docker push pangnem/cicd-example:${GITHUB_SHA::7}

      - name: Docker Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 13.125.238.228
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
            docker pull pangnem/cicd-example:${GITHUB_SHA::7}
            docker tag pangnem/cicd-example:${GITHUB_SHA::7} cicd-example
            docker stop server
            docker run -d --rm --name server -p 8080:8080 cicd-example
