# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Docker build
        run: |
          docker build -t cicdexample .
          docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
          docker tag cicd-example pangnem/cicd-example:${GITHUB_SHA::7}
          docker push pangnem/cicd-example:${GITHUB_SHA::7}
